server:
  port: 8081

spring:
  application:
    name: ChamoBank

  datasource:
    url: jdbc:h2:file:./data/SpringInventarioProductos
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true


logging:
  level:
    org.springframework: INFO
    com.myapp: DEBUG